### ISSUE TITLE
ContentView doesn't automatically resize when window is resized.

### ISSUE THREAD

**Issue by Memphiz** [Memphiz/xbmc#30]
Currently we have to manually resize the contentView (our OSXGLView) whenever the window is resized.

The current flow is as follows. We drag a corner of the window to resize the window. After the resize we are called back from OSX in:
OSXGLWindow::windowDidEndLiveResize

where we fetch the new frame rect from the window (this is the whole window including decorations) and determine the new content rect size via contentRectForFrameRect.

That size is passed to kodi via TMSG_VIDEORESIZE which in return ends up in
CWinSystemOSX::ResizeWindow

were we convert back from content rect to window frame rect via
frameRectForContentRect

and set both - the window frame (which should already be correct) and the content view frame.

The Goal is to have the content view auto resize when window size changes.  Searchword might be cocoa autolayout or nswindow autolayout (not sure).

**Comment by FernetMenta** [comment]
can't repro this issue on current branch. please check again

**Comment by FernetMenta** [comment]
the stratagy is to differentiate between internal and external resize. with Wayland we introduced this new method:
https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/WinSystem.h#L77

**Comment by FernetMenta** [comment]
https://github.com/xbmc/xbmc/commit/747dabb6e939efd13352cecb7235e26ea6050415

**Comment by Memphiz** [comment]
Ah - got it. Internal resizes are only updating gl context and height/width now - yeah that sounds good. Will try your changes asap :)

**Comment by Memphiz** [comment]
Commented on the commits. It now doesn't resize properly or me anymore. The contentview is just not properly sized now. Those performSelector additions you added don't work at all for me. Wonder how you got this running?

**Comment by Memphiz** [comment]
Something like this: https://pastebin.com/SPnkhx6G - but it still doesn't work.

Here a video how it behaves here: https://www.youtube.com/watch?v=-5AaaAMU9Fo

**Comment by FernetMenta** [comment]
https://github.com/xbmc/xbmc/commit/747dabb6e939efd13352cecb7235e26ea6050415

introduced issues. before it was working for me. something we still need to update on FinishWindowResize

**Comment by FernetMenta** [comment]
this works for me but I have no clue why: https://github.com/xbmc/xbmc/commit/fd4ff198e00de8de8f82d258301a5688e8f41bea

**Comment by FernetMenta** [comment]
pushed more fixes. works for me now

**Comment by Memphiz** [comment]
for me too - nice work - thx for finding this :)
