### ISSUE TITLE
When resizing the window in windowed mode - the position of the window jumps.

### ISSUE THREAD

**Issue by Memphiz** [Memphiz/xbmc#31]
When resizing the window in windowed mode and while dragging the lower right corner of the window - the origin of the window jumps unpredictable.

To be noted. The origin of NSWindow is the lower left corner. It might have to do with that - maybe somewhere in the code we assume the top left corner.

**Comment by FernetMenta** [comment]
https://github.com/xbmc/xbmc/commit/3a259a50b5999bea96286f5304b36679ffffb6c6
